language: java
jdk:
- oraclejdk8
sudo: required

script: gradle check
branches:
only: develop

notifications:
  email: true
  recipients:
  - carlos.gonzales@jalasoft.com
  - juana.rodriguez@fundacion-jala.org

